# Generated by Django 2.2.7 on 2019-11-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                (
                    "key",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
                ("order", models.IntegerField(unique=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={"db_table": "referral_links"},
        )
    ]
