# Generated by Django 5.1 on 2024-08-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                ("deletedAt", models.DateTimeField(null=True)),
                (
                    "key",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
                ("order", models.IntegerField(unique=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "referral_links",
            },
        ),
    ]
