# Generated by Django 2.2.6 on 2019-11-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                (
                    "key",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
                ("order", models.IntegerField(unique=True)),
            ],
        )
    ]
