services:
  api:
    command: uvicorn --factory app:create_app --host 0.0.0.0 --reload --timeout-keep-alive 600
    volumes:
      - ./docker/python:/usr/src/scripts
    stdin_open: true
    tty: true

  postgres:
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test123
