services:
  api:
    command: gunicorn app:create_app() --bind 0.0.0.0:8000 --reload --timeout 600
    volumes:
      - ./docker/python:/usr/src/scripts
    stdin_open: true
    tty: true

  mysql:
    ports:
      - 3306:3306
