version: '3.6'

volumes:
  mysql_db:
    driver: local
    name: gp_mysql_db

services:
  proxy:
    container_name: gamersplane-proxy
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/site.conf
      - ./frontend/dist:/var/www/ng
      - ./api:/var/www/api
    depends_on:
      - api

  api:
    container_name: gamersplane-api
    build:
      context: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_POST=3306
    depends_on:
      - mysql

  mysql:
    container_name: gamersplane-mysql
    image: mysql:5.7
    env_file:
      - ./.env
    volumes:
      # - ./docker/mysql:/docker-entrypoint-initdb.d
      - mysql_db:/var/lib/mysql
