version: '3.6'

volumes:
  php_logs:
    driver: local
    name: gp_php_logs
  postgres_db:
    driver: local
    name: gp_postgres_db

services:
  proxy:
    container_name: gamersplane-proxy
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/site.conf
      - ./frontend/dist:/var/www
    depends_on:
      - api

  api:
    container_name: gamersplane-api
    build:
      context: ./api
      dockerfile: Dockerfile-php
    volumes:
      - ./:/var/www/api
      - php_logs:/var/logs
    depends_on:
      - postgres

  postgres:
    container_name: gamersplane-postgres
    image: postgres:11.2-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - postgres_db:/var/lib/postgres
