name: gpv2

volumes:
  postgres_db:
    driver: local
    name: gp_postgres_db

services:
  proxy:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.${ENVIRONMENT}.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - api

  api:
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16.4
    env_file:
      - ./.env
    volumes:
      # - ./docker/postgres:/docker-entrypoint-initdb.d
      - postgres_db:/var/lib/postgres

  cache:
    image: redis:7.4-alpine

  frontend:
    build:
      context: ./frontend
      target: dev
      dockerfile: ../docker/Dockerfile-nextjs
    volumes:
        - ./frontend:/app
        # - /app/node_modules
        # - /app/.next

  postfix:
    build:
      context: ./docker/postfix
    environment:
      - POSTFIX_MYHOSTNAME
    volumes:
      - ./logs/postfix:/var/log

  opendkim:
    build:
      context: ./docker/opendkim
      args:
        - OPENDKIM_KEY
    environment:
      - OPENDKIM_SELECTOR
      - POSTFIX_MYHOSTNAME
    volumes:
      - ./logs/opendkim:/var/log
