version: '3.6'

volumes:
  php_logs:
    driver: local
    name: gp_php_logs
  mysql_db:
    driver: local
    name: gp_mysql_db

services:
  proxy:
    container_name: gamersplane-proxy
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/site.conf
      - ./frontend/dist:/var/www/ng
      - ./api:/var/www/api
    depends_on:
      - api

  api:
    container_name: gamersplane-api
    build:
      context: ./api
      dockerfile: Dockerfile-php
    volumes:
      - ./api:/var/www/api
      - php_logs:/var/logs
    depends_on:
      - mysql

  mysql:
    container_name: gamersplane-mysql
    image: mysql:5.7
    env_file:
      - ./.env
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - mysql_db:/var/lib/mysql
