version: '3.6'

volumes:
  mysql_db:
    driver: local
    name: gp_mysql_db

services:
  proxy:
    container_name: gp-proxy
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.${ENVIRONMENT}.conf:/etc/nginx/conf.d/site.conf
      - ./frontend/dist:/var/www/ng
      - ./api:/var/www/api
    depends_on:
      - api

  api:
    container_name: gp-api
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: gp-mysql
    image: mysql:5.7
    env_file:
      - ./.env
    volumes:
      # - ./docker/mysql:/docker-entrypoint-initdb.d
      - mysql_db:/var/lib/mysql

  cache:
    container_name: gp-cache
    image: redis:6.2-alpine

  postfix:
    build:
      context: ./docker/postfix
    container_name: gp-postfix
    ports:
      - "8025:25"
    environment:
      - POSTFIX_MYHOSTNAME
    volumes:
      - ./logs/postfix:/var/log

  opendkim:
    build:
      context: ./docker/opendkim
      args:
        - OPENDKIM_KEY
    container_name: gpv1-opendkim
    environment:
      - OPENDKIM_SELECTOR
      - POSTFIX_MYHOSTNAME
    volumes:
      - ./logs/opendkim:/var/log
