version: '3.6'

services:
  api:
    command: gunicorn app:app --bind 0.0.0.0:8000 --reload

  mysql:
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_PASSWORD=test123
