# Generated by Django 5.1 on 2024-08-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deletedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("genre", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "genres",
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deletedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40)),
                ("website", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "publishers",
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                ("deletedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=40)),
                ("sortName", models.CharField(max_length=40)),
                ("basics", models.JSONField(null=True)),
                ("hasCharSheet", models.BooleanField(default=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        db_column="publisherId",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="systems.publisher",
                    ),
                ),
            ],
            options={
                "db_table": "systems",
            },
        ),
        migrations.CreateModel(
            name="SystemGenre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deletedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "genre",
                    models.ForeignKey(
                        db_column="genreId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="systems.genre",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        db_column="systemId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="systems.system",
                    ),
                ),
            ],
            options={
                "db_table": "system_genres",
            },
        ),
        migrations.AddField(
            model_name="system",
            name="genres",
            field=models.ManyToManyField(
                related_name="genres", through="systems.SystemGenre", to="systems.genre"
            ),
        ),
    ]
