# Generated by Django 3.1.6 on 2021-02-23 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("systems", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=40)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("deletedAt", models.DateTimeField(null=True)),
            ],
            options={"db_table": "genres"},
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("website", models.CharField(max_length=200, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("deletedAt", models.DateTimeField(null=True)),
            ],
            options={"db_table": "publishers"},
        ),
        migrations.RemoveField(model_name="system", name="generes"),
        migrations.AlterField(
            model_name="system", name="basics", field=models.JSONField(null=True)
        ),
        migrations.CreateModel(
            name="SystemGenre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        db_column="genreId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="systems.genre",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        db_column="systemId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="systems.system",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("deletedAt", models.DateTimeField(null=True)),
            ],
            options={"db_table": "system_genres"},
        ),
        migrations.AddField(
            model_name="system",
            name="genres",
            field=models.ManyToManyField(
                related_name="genres", through="systems.SystemGenre", to="systems.Genre"
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="publisher",
            field=models.ForeignKey(
                db_column="publisherId",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="systems.publisher",
            ),
        ),
    ]
