import type { JSONContent } from "@tiptap/core";
import { generateHTML } from "@tiptap/core";
import { Color } from "@tiptap/extension-color";
import { Image } from "@tiptap/extension-image";
import { TaskItem, TaskList } from "@tiptap/extension-list";
import { Subscript } from "@tiptap/extension-subscript";
import { Superscript } from "@tiptap/extension-superscript";
import { TextAlign } from "@tiptap/extension-text-align";
import { TextStyle } from "@tiptap/extension-text-style";
import { Typography } from "@tiptap/extension-typography";
import { StarterKit } from "@tiptap/starter-kit";
import clsx from "clsx";
import { useMemo } from "react";
import { HorizontalRule } from "#/components/tiptap/tiptap-node/horizontal-rule-node/horizontal-rule-node-extension";
import "#/components/tiptap/tiptap-node/blockquote-node/blockquote-node.scss";
import "#/components/tiptap/tiptap-node/code-block-node/code-block-node.scss";
import "#/components/tiptap/tiptap-node/horizontal-rule-node/horizontal-rule-node.scss";
import "#/components/tiptap/tiptap-node/list-node/list-node.scss";
import "#/components/tiptap/tiptap-node/image-node/image-node.scss";
import "#/components/tiptap/tiptap-node/heading-node/heading-node.scss";
import "#/components/tiptap/tiptap-node/paragraph-node/paragraph-node.scss";

// Mirrors the node/mark extensions registered in #/components/Editor.tsx so
// read-only content renders identically to how it was authored, without the
// cost of mounting a full ProseMirror editor view per message.
const extensions = [
	StarterKit.configure({
		horizontalRule: false,
		link: {
			openOnClick: false,
			enableClickSelection: true,
		},
	}),
	HorizontalRule,
	TextAlign.configure({ types: ["heading", "paragraph"] }),
	TaskList,
	TaskItem.configure({ nested: true }),
	TextStyle,
	Color,
	Image,
	Typography,
	Superscript,
	Subscript,
];

export function TiptapContent({
	content,
	className,
}: {
	content: JSONContent;
	className?: string;
}) {
	const html = useMemo(() => generateHTML(content, extensions), [content]);

	return (
		<div
			className={clsx("tiptap-content ProseMirror", className)}
			// biome-ignore lint/security/noDangerouslySetInnerHtml: html is generated by Tiptap's own serializer from a fixed extension schema, not raw user input
			dangerouslySetInnerHTML={{ __html: html }}
		/>
	);
}
