# Generated by Django 3.1 on 2021-02-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deletedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "role_type",
                    models.CharField(
                        choices=[("s", "Site"), ("f", "Forum")], max_length=1, null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.user",
                    ),
                ),
            ],
            options={"db_table": "roles"},
        ),
        migrations.CreateModel(
            name="SitePermissions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission", models.CharField(max_length=64)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("deletedAt", models.DateTimeField(null=True)),
            ],
            options={"db_table": "site_permissions"},
        ),
    ]
