# Generated by Django 3.1.6 on 2021-03-04 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("permissions", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                db_column="permissionId",
                on_delete=django.db.models.deletion.PROTECT,
                to="permissions.permission",
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                db_column="roleId",
                on_delete=django.db.models.deletion.PROTECT,
                to="permissions.role",
            ),
        ),
    ]
