# Generated by Django 5.1 on 2024-08-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("permissions", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="owner",
            field=models.ForeignKey(
                db_column="userId",
                on_delete=django.db.models.deletion.PROTECT,
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                db_column="permissionId",
                on_delete=django.db.models.deletion.PROTECT,
                to="permissions.permission",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                db_column="roleId",
                on_delete=django.db.models.deletion.PROTECT,
                to="permissions.role",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles",
                through="permissions.RolePermission",
                to="permissions.permission",
            ),
        ),
    ]
