# Generated by Django 3.1 on 2021-01-12 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("auth", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("aa", "Account Activation"),
                            ("pr", "Password Reset"),
                        ],
                        max_length=2,
                    ),
                ),
                ("token", models.CharField(max_length=36)),
                ("requestedOn", models.DateTimeField(auto_now_add=True)),
                ("used", models.DateTimeField(default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auth.user",
                    ),
                ),
            ],
            options={"db_table": "tokens"},
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["token"], name="tokens_token_57b770_idx"),
        ),
    ]
