# Generated by Django 3.1 on 2021-02-04 04:06

from django.db import migrations, models
import django.db.models.deletion
import tokens.models.token


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial"), ("tokens", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="AccountActivationToken",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("tokens.token",),
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("tokens.token",),
        ),
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(
                default=tokens.models.token.Token.generate_token, max_length=36
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="user",
            field=models.ForeignKey(
                db_column="userId",
                on_delete=django.db.models.deletion.PROTECT,
                to="users.user",
            ),
        ),
    ]
