# Generated by Django 3.1 on 2021-01-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tokens", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="AccountActivation",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("tokens.token",),
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("tokens.token",),
        ),
    ]
