# Generated by Django 3.1 on 2021-01-12 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tokens", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("tokens.token",),
        )
    ]
