# Generated by Django 5.1 on 2024-08-23 13:42

import forums.models.forum
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deletedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(null=True)),
                (
                    "forumType",
                    models.CharField(
                        choices=[("f", "Forum"), ("c", "Category")],
                        default="f",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "heritage",
                    forums.models.forum.HeritageField(max_length=25, null=True),
                ),
                ("order", models.IntegerField()),
                ("threadCount", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "forums",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deletedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("body", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[("d", "Draft"), ("p", "Post"), ("r", "Revision")],
                        default="d",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "db_table": "posts",
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deletedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("sticky", models.BooleanField(default=False)),
                ("locked", models.BooleanField(default=False)),
                ("allowRolls", models.BooleanField(default=False)),
                ("allowDraws", models.BooleanField(default=False)),
                ("postCount", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "threads",
            },
        ),
    ]
