# Generated by Django 3.1.7 on 2021-04-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forums", "0001_initial"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="game",
            field=models.ForeignKey(
                db_column="gameId",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="forum",
            name="parent",
            field=models.ForeignKey(
                db_column="parentId",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="forums.forum",
            ),
        ),
    ]
