# Generated by Django 5.1 on 2024-08-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forums", "0001_initial"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="game",
            field=models.ForeignKey(
                db_column="gameId",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="forum",
            name="parent",
            field=models.ForeignKey(
                db_column="parentId",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="forums.forum",
            ),
        ),
    ]
