# Generated by Django 5.1 on 2024-08-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("characters", "0001_initial"),
        ("forums", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                db_column="authorId",
                on_delete=django.db.models.deletion.PROTECT,
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="postedAs",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="characters.character",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="revisionOf",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="forums.post"
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="firstPost",
            field=models.ForeignKey(
                db_column="firstPostId",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="first_post",
                to="forums.post",
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="forum",
            field=models.ForeignKey(
                db_column="forumId",
                on_delete=django.db.models.deletion.PROTECT,
                to="forums.forum",
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="lastPost",
            field=models.ForeignKey(
                db_column="lastPostId",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="last_post",
                to="forums.post",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="thread",
            field=models.ForeignKey(
                db_column="threadId",
                on_delete=django.db.models.deletion.PROTECT,
                to="forums.thread",
            ),
        ),
        migrations.AddIndex(
            model_name="forum",
            index=models.Index(fields=["parent"], name="forums_parentI_9c0c75_idx"),
        ),
        migrations.AddIndex(
            model_name="forum",
            index=models.Index(fields=["heritage"], name="forums_heritag_63a2ec_idx"),
        ),
    ]
