#!/bin/bash

docker exec -w /usr/src/app/scripts gamersplane-api './clear_db.py'
docker exec -w /usr/src/app/src gamersplane-api ./manage.py migrate
docker exec -w /usr/src/app/scripts gamersplane-api './populate_db.py'
