/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as PmsIndexRouteImport } from './routes/pms/index'
import { Route as UserUserIdRouteImport } from './routes/user.$userId'
import { Route as ToolsDiceRouteImport } from './routes/tools/dice'
import { Route as ToolsCardsRouteImport } from './routes/tools/cards'
import { Route as RegisterSuccessRouteImport } from './routes/register/success'
import { Route as RegisterResendRouteImport } from './routes/register/resend'
import { Route as PmsSendRouteImport } from './routes/pms/send'
import { Route as PmsReplyRouteImport } from './routes/pms/reply'
import { Route as PmsPmIdRouteImport } from './routes/pms/$pmId'
import { Route as ForumsChar123ForumIdChar125RouteImport } from './routes/forums/{-$forumId}'
import { Route as ForumsThreadThreadIdRouteImport } from './routes/forums/thread.$threadId'
import { Route as ForumsNewThreadForumIdRouteImport } from './routes/forums/new-thread.$forumId'
import { Route as ForumsEditPostPostIdRouteImport } from './routes/forums/edit-post.$postId'

const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsIndexRoute = PmsIndexRouteImport.update({
  id: '/pms/',
  path: '/pms/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDiceRoute = ToolsDiceRouteImport.update({
  id: '/tools/dice',
  path: '/tools/dice',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCardsRoute = ToolsCardsRouteImport.update({
  id: '/tools/cards',
  path: '/tools/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/register/success',
  path: '/register/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterResendRoute = RegisterResendRouteImport.update({
  id: '/register/resend',
  path: '/register/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsSendRoute = PmsSendRouteImport.update({
  id: '/pms/send',
  path: '/pms/send',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsReplyRoute = PmsReplyRouteImport.update({
  id: '/pms/reply',
  path: '/pms/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsPmIdRoute = PmsPmIdRouteImport.update({
  id: '/pms/$pmId',
  path: '/pms/$pmId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsChar123ForumIdChar125Route =
  ForumsChar123ForumIdChar125RouteImport.update({
    id: '/forums/{-$forumId}',
    path: '/forums/{-$forumId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForumsThreadThreadIdRoute = ForumsThreadThreadIdRouteImport.update({
  id: '/forums/thread/$threadId',
  path: '/forums/thread/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsNewThreadForumIdRoute = ForumsNewThreadForumIdRouteImport.update({
  id: '/forums/new-thread/$forumId',
  path: '/forums/new-thread/$forumId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsEditPostPostIdRoute = ForumsEditPostPostIdRouteImport.update({
  id: '/forums/edit-post/$postId',
  path: '/forums/edit-post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/systems': typeof SystemsRoute
  '/forums/{-$forumId}': typeof ForumsChar123ForumIdChar125Route
  '/pms/$pmId': typeof PmsPmIdRoute
  '/pms/reply': typeof PmsReplyRoute
  '/pms/send': typeof PmsSendRoute
  '/register/resend': typeof RegisterResendRoute
  '/register/success': typeof RegisterSuccessRoute
  '/tools/cards': typeof ToolsCardsRoute
  '/tools/dice': typeof ToolsDiceRoute
  '/user/$userId': typeof UserUserIdRoute
  '/pms/': typeof PmsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/forums/edit-post/$postId': typeof ForumsEditPostPostIdRoute
  '/forums/new-thread/$forumId': typeof ForumsNewThreadForumIdRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/systems': typeof SystemsRoute
  '/forums/{-$forumId}': typeof ForumsChar123ForumIdChar125Route
  '/pms/$pmId': typeof PmsPmIdRoute
  '/pms/reply': typeof PmsReplyRoute
  '/pms/send': typeof PmsSendRoute
  '/register/resend': typeof RegisterResendRoute
  '/register/success': typeof RegisterSuccessRoute
  '/tools/cards': typeof ToolsCardsRoute
  '/tools/dice': typeof ToolsDiceRoute
  '/user/$userId': typeof UserUserIdRoute
  '/pms': typeof PmsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/forums/edit-post/$postId': typeof ForumsEditPostPostIdRoute
  '/forums/new-thread/$forumId': typeof ForumsNewThreadForumIdRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/systems': typeof SystemsRoute
  '/forums/{-$forumId}': typeof ForumsChar123ForumIdChar125Route
  '/pms/$pmId': typeof PmsPmIdRoute
  '/pms/reply': typeof PmsReplyRoute
  '/pms/send': typeof PmsSendRoute
  '/register/resend': typeof RegisterResendRoute
  '/register/success': typeof RegisterSuccessRoute
  '/tools/cards': typeof ToolsCardsRoute
  '/tools/dice': typeof ToolsDiceRoute
  '/user/$userId': typeof UserUserIdRoute
  '/pms/': typeof PmsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/forums/edit-post/$postId': typeof ForumsEditPostPostIdRoute
  '/forums/new-thread/$forumId': typeof ForumsNewThreadForumIdRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/community-guidelines'
    | '/login'
    | '/privacy-policy'
    | '/profile'
    | '/systems'
    | '/forums/{-$forumId}'
    | '/pms/$pmId'
    | '/pms/reply'
    | '/pms/send'
    | '/register/resend'
    | '/register/success'
    | '/tools/cards'
    | '/tools/dice'
    | '/user/$userId'
    | '/pms/'
    | '/register/'
    | '/forums/edit-post/$postId'
    | '/forums/new-thread/$forumId'
    | '/forums/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/community-guidelines'
    | '/login'
    | '/privacy-policy'
    | '/profile'
    | '/systems'
    | '/forums/{-$forumId}'
    | '/pms/$pmId'
    | '/pms/reply'
    | '/pms/send'
    | '/register/resend'
    | '/register/success'
    | '/tools/cards'
    | '/tools/dice'
    | '/user/$userId'
    | '/pms'
    | '/register'
    | '/forums/edit-post/$postId'
    | '/forums/new-thread/$forumId'
    | '/forums/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/community-guidelines'
    | '/login'
    | '/privacy-policy'
    | '/profile'
    | '/systems'
    | '/forums/{-$forumId}'
    | '/pms/$pmId'
    | '/pms/reply'
    | '/pms/send'
    | '/register/resend'
    | '/register/success'
    | '/tools/cards'
    | '/tools/dice'
    | '/user/$userId'
    | '/pms/'
    | '/register/'
    | '/forums/edit-post/$postId'
    | '/forums/new-thread/$forumId'
    | '/forums/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  SystemsRoute: typeof SystemsRoute
  ForumsChar123ForumIdChar125Route: typeof ForumsChar123ForumIdChar125Route
  PmsPmIdRoute: typeof PmsPmIdRoute
  PmsReplyRoute: typeof PmsReplyRoute
  PmsSendRoute: typeof PmsSendRoute
  RegisterResendRoute: typeof RegisterResendRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  ToolsCardsRoute: typeof ToolsCardsRoute
  ToolsDiceRoute: typeof ToolsDiceRoute
  UserUserIdRoute: typeof UserUserIdRoute
  PmsIndexRoute: typeof PmsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ForumsEditPostPostIdRoute: typeof ForumsEditPostPostIdRoute
  ForumsNewThreadForumIdRoute: typeof ForumsNewThreadForumIdRoute
  ForumsThreadThreadIdRoute: typeof ForumsThreadThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/': {
      id: '/pms/'
      path: '/pms'
      fullPath: '/pms/'
      preLoaderRoute: typeof PmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/dice': {
      id: '/tools/dice'
      path: '/tools/dice'
      fullPath: '/tools/dice'
      preLoaderRoute: typeof ToolsDiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cards': {
      id: '/tools/cards'
      path: '/tools/cards'
      fullPath: '/tools/cards'
      preLoaderRoute: typeof ToolsCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/success': {
      id: '/register/success'
      path: '/register/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/resend': {
      id: '/register/resend'
      path: '/register/resend'
      fullPath: '/register/resend'
      preLoaderRoute: typeof RegisterResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/send': {
      id: '/pms/send'
      path: '/pms/send'
      fullPath: '/pms/send'
      preLoaderRoute: typeof PmsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/reply': {
      id: '/pms/reply'
      path: '/pms/reply'
      fullPath: '/pms/reply'
      preLoaderRoute: typeof PmsReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/$pmId': {
      id: '/pms/$pmId'
      path: '/pms/$pmId'
      fullPath: '/pms/$pmId'
      preLoaderRoute: typeof PmsPmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/{-$forumId}': {
      id: '/forums/{-$forumId}'
      path: '/forums/{-$forumId}'
      fullPath: '/forums/{-$forumId}'
      preLoaderRoute: typeof ForumsChar123ForumIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/thread/$threadId': {
      id: '/forums/thread/$threadId'
      path: '/forums/thread/$threadId'
      fullPath: '/forums/thread/$threadId'
      preLoaderRoute: typeof ForumsThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/new-thread/$forumId': {
      id: '/forums/new-thread/$forumId'
      path: '/forums/new-thread/$forumId'
      fullPath: '/forums/new-thread/$forumId'
      preLoaderRoute: typeof ForumsNewThreadForumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/edit-post/$postId': {
      id: '/forums/edit-post/$postId'
      path: '/forums/edit-post/$postId'
      fullPath: '/forums/edit-post/$postId'
      preLoaderRoute: typeof ForumsEditPostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  SystemsRoute: SystemsRoute,
  ForumsChar123ForumIdChar125Route: ForumsChar123ForumIdChar125Route,
  PmsPmIdRoute: PmsPmIdRoute,
  PmsReplyRoute: PmsReplyRoute,
  PmsSendRoute: PmsSendRoute,
  RegisterResendRoute: RegisterResendRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  ToolsCardsRoute: ToolsCardsRoute,
  ToolsDiceRoute: ToolsDiceRoute,
  UserUserIdRoute: UserUserIdRoute,
  PmsIndexRoute: PmsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ForumsEditPostPostIdRoute: ForumsEditPostPostIdRoute,
  ForumsNewThreadForumIdRoute: ForumsNewThreadForumIdRoute,
  ForumsThreadThreadIdRoute: ForumsThreadThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
