/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as PmsIndexRouteImport } from './routes/pms/index'
import { Route as RegisterSuccessRouteImport } from './routes/register/success'
import { Route as RegisterResendRouteImport } from './routes/register/resend'
import { Route as PmsSendRouteImport } from './routes/pms/send'
import { Route as PmsReplyRouteImport } from './routes/pms/reply'
import { Route as PmsPmIDRouteImport } from './routes/pms/$pmID'

const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsIndexRoute = PmsIndexRouteImport.update({
  id: '/pms/',
  path: '/pms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/register/success',
  path: '/register/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterResendRoute = RegisterResendRouteImport.update({
  id: '/register/resend',
  path: '/register/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsSendRoute = PmsSendRouteImport.update({
  id: '/pms/send',
  path: '/pms/send',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsReplyRoute = PmsReplyRouteImport.update({
  id: '/pms/reply',
  path: '/pms/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsPmIDRoute = PmsPmIDRouteImport.update({
  id: '/pms/$pmID',
  path: '/pms/$pmID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/systems': typeof SystemsRoute
  '/pms/$pmID': typeof PmsPmIDRoute
  '/pms/reply': typeof PmsReplyRoute
  '/pms/send': typeof PmsSendRoute
  '/register/resend': typeof RegisterResendRoute
  '/register/success': typeof RegisterSuccessRoute
  '/pms/': typeof PmsIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/systems': typeof SystemsRoute
  '/pms/$pmID': typeof PmsPmIDRoute
  '/pms/reply': typeof PmsReplyRoute
  '/pms/send': typeof PmsSendRoute
  '/register/resend': typeof RegisterResendRoute
  '/register/success': typeof RegisterSuccessRoute
  '/pms': typeof PmsIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/systems': typeof SystemsRoute
  '/pms/$pmID': typeof PmsPmIDRoute
  '/pms/reply': typeof PmsReplyRoute
  '/pms/send': typeof PmsSendRoute
  '/register/resend': typeof RegisterResendRoute
  '/register/success': typeof RegisterSuccessRoute
  '/pms/': typeof PmsIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/login'
    | '/profile'
    | '/systems'
    | '/pms/$pmID'
    | '/pms/reply'
    | '/pms/send'
    | '/register/resend'
    | '/register/success'
    | '/pms/'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/login'
    | '/profile'
    | '/systems'
    | '/pms/$pmID'
    | '/pms/reply'
    | '/pms/send'
    | '/register/resend'
    | '/register/success'
    | '/pms'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/login'
    | '/profile'
    | '/systems'
    | '/pms/$pmID'
    | '/pms/reply'
    | '/pms/send'
    | '/register/resend'
    | '/register/success'
    | '/pms/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SystemsRoute: typeof SystemsRoute
  PmsPmIDRoute: typeof PmsPmIDRoute
  PmsReplyRoute: typeof PmsReplyRoute
  PmsSendRoute: typeof PmsSendRoute
  RegisterResendRoute: typeof RegisterResendRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  PmsIndexRoute: typeof PmsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/': {
      id: '/pms/'
      path: '/pms'
      fullPath: '/pms/'
      preLoaderRoute: typeof PmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/success': {
      id: '/register/success'
      path: '/register/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/resend': {
      id: '/register/resend'
      path: '/register/resend'
      fullPath: '/register/resend'
      preLoaderRoute: typeof RegisterResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/send': {
      id: '/pms/send'
      path: '/pms/send'
      fullPath: '/pms/send'
      preLoaderRoute: typeof PmsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/reply': {
      id: '/pms/reply'
      path: '/pms/reply'
      fullPath: '/pms/reply'
      preLoaderRoute: typeof PmsReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms/$pmID': {
      id: '/pms/$pmID'
      path: '/pms/$pmID'
      fullPath: '/pms/$pmID'
      preLoaderRoute: typeof PmsPmIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SystemsRoute: SystemsRoute,
  PmsPmIDRoute: PmsPmIDRoute,
  PmsReplyRoute: PmsReplyRoute,
  PmsSendRoute: PmsSendRoute,
  RegisterResendRoute: RegisterResendRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  PmsIndexRoute: PmsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
