# Generated by Django 3.0 on 2020-02-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=24)),
                ("password", models.CharField(max_length=64)),
                ("salt", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                ("joinDate", models.DateTimeField(auto_now=True)),
                ("activatedOn", models.DateTimeField(null=True)),
                ("lastActivity", models.DateTimeField(null=True)),
                ("reference", models.CharField(max_length=200, null=True)),
                ("enableFilter", models.BooleanField(default=True)),
                ("showAvatars", models.BooleanField(default=True)),
                ("avatarExt", models.CharField(max_length=3, null=True)),
                ("timezone", models.CharField(default="Europe/London", max_length=20)),
                ("showTZ", models.BooleanField(null=True)),
                ("realName", models.CharField(max_length=50, null=True)),
                ("gender", models.CharField(max_length=1, null=True)),
                ("birthday", models.DateField(null=True)),
                ("showAge", models.BooleanField(null=True)),
                ("location", models.CharField(max_length=100, null=True)),
                ("aim", models.CharField(max_length=50, null=True)),
                ("gmail", models.CharField(max_length=50, null=True)),
                ("twitter", models.CharField(max_length=50, null=True)),
                ("stream", models.CharField(max_length=50, null=True)),
                ("games", models.CharField(max_length=200, null=True)),
                ("newGameMail", models.BooleanField(default=True)),
                ("postSide", models.CharField(default="r", max_length=1)),
                ("suspendedUntil", models.DateTimeField(null=True)),
                ("banned", models.BooleanField(default=False)),
            ],
            options={"db_table": "users"},
        )
    ]
