# Generated by Django 3.0 on 2020-02-18 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("auth", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requestedOn", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=16)),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="auth.User"
                    ),
                ),
            ],
            options={"db_table": "password_resets"},
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(fields=["key"], name="password_re_key_2e4f86_idx"),
        ),
    ]
