"""Create deck type and decks models

Revision ID: 0ed57e6827c2
Revises: 8b16c637a42c
Create Date: 2026-08-26 00:03:34.862348

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ed57e6827c2"
down_revision: Union[str, None] = "8b16c637a42c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deck_types",
        sa.Column("short", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("deck_size", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("short"),
    )
    op.create_table(
        "decks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.String(length=10), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("order", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("last_shuffled", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["deck_types.short"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deck_permissions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "deck_id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deck_permissions")
    op.drop_table("decks")
    op.drop_table("deck_types")
    # ### end Alembic commands ###
