"""Starting forums work

Revision ID: 3217bdd97916
Revises: 58fcc9273b2f
Create Date: 2026-08-06 16:31:55.285618

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3217bdd97916"
down_revision: Union[str, None] = "58fcc9273b2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forums",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("forum_type", sa.String(length=1), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("heritage", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=True),
        sa.Column("thread_count", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["forums.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_forums_heritage",
        "forums",
        ["heritage"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_forums_parent_id"), "forums", ["parent_id"], unique=False)
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("system_id", sa.String(length=20), nullable=False),
        sa.Column("gm_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("post_frequency", sa.String(length=4), nullable=False),
        sa.Column("num_players", sa.Integer(), nullable=False),
        sa.Column("chars_per_player", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("char_gen_info", sa.Text(), nullable=True),
        sa.Column("root_forum_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.Column("retired", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["gm_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["root_forum_id"],
            ["forums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(
        "fk_forums_game_id_games",
        "forums",
        "games",
        ["game_id"],
        ["id"],
    )
    op.create_table(
        "game_allowed_systems",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("system_id", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("game_id", "system_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_allowed_systems")
    op.drop_constraint("fk_forums_game_id_games", "forums", type_="foreignkey")
    op.drop_table("games")
    op.drop_index(op.f("ix_forums_parent_id"), table_name="forums")
    op.drop_index("ix_forums_heritage", table_name="forums", postgresql_using="gin")
    op.drop_table("forums")
    # ### end Alembic commands ###
