"""Create character sheet favorites

Revision ID: a7c37f2c3553
Revises: 0ed57e6827c2
Create Date: 2026-09-08 21:07:34.752101

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7c37f2c3553"
down_revision: Union[str, None] = "0ed57e6827c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_sheet_favorites",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("character_sheet_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_sheet_id"],
            ["character_sheets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "character_sheet_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_sheet_favorites")
    # ### end Alembic commands ###
