# Generated by Django 3.1.7 on 2021-04-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forums", "0001_initial"),
        ("users", "0003_usermeta"),
        ("permissions", "0002_auto_20210304_0314"),
        ("systems", "0002_auto_20210223_0418"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now=True)),
                ("start", models.DateTimeField(auto_now=True)),
                ("postFrequency", models.CharField(max_length=4)),
                ("numPlayers", models.SmallIntegerField()),
                ("charsPerPlayer", models.SmallIntegerField(default=1)),
                ("description", models.TextField(null=True)),
                ("charGenInfo", models.TextField(null=True)),
                (
                    "status",
                    models.BooleanField(
                        choices=[("True", "Open"), ("False", "Closed")], default="True"
                    ),
                ),
                ("public", models.BooleanField()),
                ("retired", models.DateTimeField(null=True)),
                (
                    "allowedCharSheets",
                    models.ManyToManyField(
                        limit_choices_to={"hasCharSheet": True},
                        related_name="_game_allowedCharSheets_+",
                        to="systems.System",
                    ),
                ),
                (
                    "gm",
                    models.ForeignKey(
                        db_column="gmId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.user",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="groupId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="permissions.role",
                    ),
                ),
                (
                    "rootForum",
                    models.ForeignKey(
                        db_column="forumId",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="forums.forum",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        db_column="systemId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="systems.system",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("deletedAt", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "games",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("removed", "Removed"),
                            ("left", "Left"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        db_column="gameId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.user",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("deletedAt", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "players",
            },
        ),
    ]
