# Generated by Django 5.1 on 2024-08-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deletedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("removed", "Removed"),
                            ("left", "Left"),
                        ],
                        max_length=8,
                    ),
                ),
            ],
            options={
                "db_table": "players",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deletedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now=True)),
                ("start", models.DateTimeField(auto_now=True)),
                ("postFrequency", models.CharField(max_length=4)),
                ("numPlayers", models.SmallIntegerField()),
                ("charsPerPlayer", models.SmallIntegerField(default=1)),
                ("description", models.TextField(null=True)),
                ("charGenInfo", models.TextField(null=True)),
                ("status", models.BooleanField(default=(True,))),
                ("public", models.BooleanField()),
                ("retired", models.DateTimeField(null=True)),
                (
                    "allowedCharSheets",
                    models.ManyToManyField(
                        limit_choices_to={"hasCharSheet": True},
                        related_name="+",
                        to="systems.system",
                    ),
                ),
            ],
            options={
                "db_table": "games",
            },
        ),
    ]
