# Generated by Django 5.1 on 2024-08-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forums", "0003_initial"),
        ("games", "0001_initial"),
        ("permissions", "0001_initial"),
        ("systems", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="gm",
            field=models.ForeignKey(
                db_column="gmId",
                on_delete=django.db.models.deletion.PROTECT,
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="group",
            field=models.ForeignKey(
                db_column="groupId",
                on_delete=django.db.models.deletion.PROTECT,
                to="permissions.role",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="rootForum",
            field=models.ForeignKey(
                db_column="forumId",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="forums.forum",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="system",
            field=models.ForeignKey(
                db_column="systemId",
                on_delete=django.db.models.deletion.PROTECT,
                to="systems.system",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="game",
            field=models.ForeignKey(
                db_column="gameId",
                on_delete=django.db.models.deletion.PROTECT,
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                db_column="userId",
                on_delete=django.db.models.deletion.PROTECT,
                to="users.user",
            ),
        ),
    ]
