# Generated by Django 5.1 on 2024-08-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=24, unique=True)),
                ("password", models.CharField(max_length=64)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("joinDate", models.DateTimeField(auto_now=True)),
                ("activatedOn", models.DateTimeField(null=True)),
                ("lastActivity", models.DateTimeField(null=True)),
                ("suspendedUntil", models.DateTimeField(null=True)),
                ("banned", models.DateTimeField(null=True)),
                ("admin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserMeta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("avatarExt", "Avatar Extension"),
                            ("location", "Location"),
                            ("newGameMail", "New Game Mail"),
                            ("postSide", "Post Side"),
                            ("reference", "Reference"),
                            ("showAvatars", "Show Avatars"),
                            ("showTZ", "Show Timezone"),
                            ("timezone", "Timezone"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meta",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_meta",
            },
        ),
        migrations.CreateModel(
            name="UserRoles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deletedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        db_column="roleId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="permissions.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_roles",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                related_name="users", through="users.UserRoles", to="permissions.role"
            ),
        ),
    ]
