# Generated by Django 3.1 on 2021-02-16 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=24)),
                ("password", models.CharField(max_length=64)),
                ("salt", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                ("joinDate", models.DateTimeField(auto_now=True)),
                ("activatedOn", models.DateTimeField(null=True)),
                ("lastActivity", models.DateTimeField(null=True)),
                ("suspendedUntil", models.DateTimeField(null=True)),
                ("banned", models.DateTimeField(null=True)),
                ("admin", models.BooleanField(default=True)),
            ],
            options={"db_table": "users"},
        )
    ]
