# Generated by Django 3.1 on 2021-02-16 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("users", "0001_initial"), ("permissions", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="UserRoles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="roleId",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="permissions.Role",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("deletedAt", models.DateTimeField(null=True)),
            ],
            options={"db_table": "user_roles"},
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                related_name="users", through="users.UserRoles", to="permissions.Role"
            ),
        ),
        migrations.AddField(
            model_name="userroles",
            name="user",
            field=models.ForeignKey(
                db_column="userId",
                on_delete=django.db.models.deletion.PROTECT,
                to="users.user",
            ),
        ),
    ]
