# Generated by Django 3.1.6 on 2021-02-25 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0002_add_foreign_key")]

    operations = [
        migrations.CreateModel(
            name="UserMeta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meta",
                        to="users.user",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("avatarExt", "Avatar Extension"),
                            ("location", "Location"),
                            ("newGameMail", "New Game Mail"),
                            ("postSide", "Post Side"),
                            ("reference", "Reference"),
                            ("showAvatars", "Show Avatars"),
                            ("showTZ", "Show Timezone"),
                            ("timezone", "Timezone"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(max_length=200)),
            ],
            options={"db_table": "user_meta"},
        )
    ]
